### ISSUE TITLE
Add /home/avd/.local/bin to /etc/sudeors secure-path

### ISSUE THREAD

**Issue by nathansharief** [arista-netdevops-community/avd-all-in-one-container#28]
Running into an issue running ansible commands using sudo as the commands are not found. 
I have tried running as "sudo $(which ansible-playbook)" to bypass the default sudoer secure-path but this fails as python is used to import the ansible module which is still located in /home/avd/.local/ . This is not present in sys.path when using sudo and python is unable to find ansible.

Can /home/avd/.local/bin be added to secure-path in /etc/sudoers as a possible fix?
This is an issue when using gitlab runners which import repositories as root user.

**Comment by carlbuchmann** [comment]
@nathansharief I don't recommend running Ansible commands with sudo. What is your requirement to leverage sudo?

**Comment by nathansharief** [comment]
We are using gitlab runners which import the remote respository with root privileges. Without the ability to run ansible with sudo we are unable to use the container with Gitlab CI/CD. What are the concerns using ansible as root within a temporary container used to run the jobs on a runner? The avd user is already part of the sudo group as I can see.

**Comment by ankudinov** [comment]
I'll follow-up with Nathan unicast. Closing this issue as community all-in-one will be replaced with AVD container images in the close future. AVD has a large community and all issues must be addressed as part of AVD development activities if applicable to the new images. Also technically building a Gitlab runner with AVD is a very delicate topic that should be discussed separately.
